// arealformal.js: oversetter tallkoder for arealformål til tekst.
//
// Plantjenesten svarer med koder som "2011" i stedet for "Kjøreveg".
// Denne listen er hentet fra Geonorge sine offisielle SOSI-kodelister:
//   https://register.geonorge.no/sosi-kodelister/plan/reguleringsplan/rparealformål
//   https://register.geonorge.no/sosi-kodelister/plan/pbl-1985/arealbruk
// Nyere planer bruker firesifrede koder, eldre planer (plan- og bygningsloven
// av 1985) bruker tresifrede koder, så de kan ligge i samme liste.

const AREALFORMAL = {
  // Reguleringsplaner etter plan- og bygningsloven 2008 (firesifrede koder)
  '1000': "Bebyggelse og anlegg - generalisert (utgått)",
  '1001': "Bebyggelse og anlegg",
  '1110': "Boligbebyggelse",
  '1111': "Boligbebyggelse, frittliggende småhus",
  '1112': "Boligbebyggelse, konsentrerte småhus",
  '1113': "Boligbebyggelse, blokker",
  '1114': "Studentboliger",
  '1119': "Garasjeanlegg for bolig- eller fritidsbebyggelse",
  '1120': "Fritidsbebyggelse",
  '1121': "Frittliggende fritidsbebyggelse",
  '1122': "Konsentrert fritidsbebyggelse",
  '1123': "Fritidsbebyggelse, blokker",
  '1124': "Kolonihage",
  '1130': "Sentrumsformål",
  '1140': "Kjøpesenter",
  '1150': "Forretninger",
  '1160': "Bebyggelse for offentlig eller privat tjenesteyting",
  '1161': "Barnehage",
  '1162': "Undervisning",
  '1163': "Institusjon (utgått)",
  '1164': "Forsamlingslokale for tro- og livssynsutøvelse",
  '1165': "Forsamlingslokale",
  '1166': "Administrasjon",
  '1167': "Kulturinstitusjon",
  '1168': "Helse- eller omsorgsinstitusjon",
  '1169': "Nærmere angitt offentlig eller privat tjenesteyting",
  '1170': "Fritids- og turistformål",
  '1171': "Utleiehytter",
  '1172': "Fornøyelsespark eller temapark",
  '1173': "Campingplass",
  '1174': "Leirplass",
  '1200': "Råstoffutvinning",
  '1201': "Steinbrudd og masseuttak",
  '1202': "Massemottak",
  '1300': "Næringsbebyggelse",
  '1310': "Kontor",
  '1320': "Hotell og overnatting",
  '1330': "Bevertning",
  '1340': "Industri",
  '1341': "Kraftkrevende industri",
  '1342': "Datasenter",
  '1350': "Lager",
  '1360': "Bensinstasjon eller vegserviceanlegg",
  '1390': "Nærmere angitt næring",
  '1400': "Idrettsanlegg",
  '1410': "Skianlegg",
  '1420': "Skiløypetrasé",
  '1430': "Idrettsstadion",
  '1440': "Nærmiljøanlegg",
  '1450': "Golfbane",
  '1460': "Motorsportanlegg",
  '1470': "Skytebane",
  '1490': "Nærmere angitt idrettsanlegg",
  '1500': "Andre typer anlegg",
  '1501': "Godsterminal",
  '1502': "Godslager",
  '1510': "Energianlegg",
  '1520': "Fjernvarmeanlegg",
  '1530': "Vindkraftanlegg",
  '1531': "Solkraftanlegg",
  '1540': "Vann- og avløpanlegg",
  '1541': "Vannforsyningsanlegg",
  '1542': "Avløpsanlegg",
  '1543': "Overvannsanlegg",
  '1550': "Renovasjonsanlegg",
  '1560': "Nærmere angitt kommunalteknisk anlegg",
  '1570': "Telekommunikasjonsanlegg",
  '1587': "Småbåtanlegg i sjø og vassdrag",
  '1588': "Småbåtanlegg i sjø og vassdrag med tilhørende strandsone",
  '1589': "Uthus, naust eller badehus",
  '1590': "Nærmere angitte andre typer anlegg",
  '1600': "Uteoppholdsarealer",
  '1610': "Lekeplass",
  '1620': "Gårdsplass",
  '1630': "Parsellhage",
  '1640': "Urbant landbruk",
  '1690': "Nærmere angitte uteoppholdsarealer",
  '1700': "Gravplass",
  '1710': "Krematorium",
  '1730': "Bygg og anlegg for gravplass",
  '1800': "Bebyggelse og anlegg kombinert i samsvar med angitte bestemmelser",
  '1801': "Kombinert bolig og forretning",
  '1802': "Kombinert bolig, forretning og kontor",
  '1803': "Kombinert bolig og tjenesteyting",
  '1804': "Kombinert bolig og kontor",
  '1810': "Kombinert forretning og kontor",
  '1811': "Kombinert forretning, kontor og industri",
  '1812': "Kombinert forretning og industri",
  '1813': "Kombinert forretning, kontor og tjenesteyting",
  '1814': "Kombinert forretning og tjenesteyting",
  '1820': "Næring/kontor (utgått)",
  '1821': "Næring/kontor/industri (utgått)",
  '1822': "Næring/industri (utgått)",
  '1823': "Næring/kontor/tjenesteyting (utgått)",
  '1824': "Kombinert næring og tjenesteyting",
  '1825': "Kombinert kontor og lager",
  '1826': "Kombinert industri og lager",
  '1830': "Kombinert kontor og industri",
  '1831': "Kombinert kontor og tjenesteyting",
  '1900': "Bebyggelse og anlegg kombinert med andre angitte hovedformål",
  '2000': "Samferdselsanlegg og teknisk infrastruktur (utgått)",
  '2001': "Samferdselsanlegg og teknisk infrastruktur",
  '2010': "Veg",
  '2011': "Kjøreveg",
  '2012': "Fortau",
  '2013': "Torg",
  '2014': "Gatetun",
  '2015': "Gang- og sykkelveg",
  '2016': "Gangveg, gangareal eller gågate",
  '2017': "Sykkelanlegg",
  '2018': "Annen veggrunn, tekniske anlegg",
  '2019': "Annen veggrunn, grøntareal",
  '2020': "Bane",
  '2021': "Jernbane",
  '2022': "Sporveg",
  '2023': "Taubane",
  '2024': "Stasjons- eller terminalbygg",
  '2025': "Holdeplass eller plattform",
  '2026': "Leskur eller plattformtak",
  '2027': "Tekniske bygninger og konstruksjoner",
  '2028': "Annen banegrunn, tekniske anlegg",
  '2029': "Annen banegrunn, grøntareal",
  '2030': "Lufthavn",
  '2031': "Lufthavn, banesystem",
  '2032': "Lufthavn - terminalbygg (utgått)",
  '2033': "Lufthavn- hangarer/administrasjonsbygg (utgått)",
  '2034': "Landingsplass for helikopter o.a.",
  '2035': "Lufthavn, bygninger",
  '2040': "Havn",
  '2041': "Kai",
  '2042': "Havneterminaler",
  '2043': "Havnelager",
  '2044': "Molo",
  '2045': "Navigasjonsinstallasjon",
  '2050': "Hovednett for sykkel",
  '2060': "Kollektivnett",
  '2061': "Trasé for nærmere angitt kollektivtransport",
  '2070': "Kollektivknutepunkt",
  '2071': "Kollektivanlegg",
  '2072': "Kollektivterminal",
  '2073': "Kollektivholdeplass",
  '2074': "Pendler- eller innfartsparkering",
  '2080': "Parkering",
  '2081': "Rasteplass",
  '2082': "Parkeringsplasser",
  '2083': "Parkeringshus eller -anlegg",
  '2100': "Trase for teknisk infrastruktur (utgått)",
  '2101': "Teknisk infrastruktur",
  '2110': "Kraftledning, energinett",
  '2120': "Fjernvarmenett",
  '2140': "Vann- og avløpsnett",
  '2141': "Vannforsyningsnett",
  '2142': "Avløpsnett",
  '2143': "Trasé for overvann",
  '2150': "Trasé for avfallssug",
  '2160': "Telekommunikasjonsnett",
  '2170': "Sikringsanlegg",
  '2180': "Trasé for nærmere angitt teknisk infrastruktur",
  '2190': "Kombinerte tekniske infrastrukturtraseer",
  '2200': "Faunapassasje",
  '2800': "Samferdselsanlegg og teknisk infrastruktur kombinert i samsvar med angitte bestemmelser",
  '2900': "Samferdselsanlegg eller teknisk infrastruktur kombinert med andre angitte hovedformål",
  '3000': "Grønnstruktur - generalisert (utgått)",
  '3001': "Grønnstruktur",
  '3002': "Blågrønnstruktur",
  '3020': "Naturområde",
  '3030': "Turdrag",
  '3031': "Turveg",
  '3040': "Friområde",
  '3041': "Badeplass eller -område",
  '3050': "Park",
  '3060': "Vegetasjonsskjerm",
  '3061': "Vannspeil",
  '3100': "Overvannstiltak",
  '3110': "Infiltrasjon, fordrøyning eller avledning",
  '3800': "Grønnstruktur kombinert i samsvar med angitte bestemmelser",
  '3900': "Grønnstruktur kombinert med andre angitte hovedformål",
  '4000': "Forsvaret - generalisert (utgått)",
  '4001': "Forsvaret",
  '4010': "Ulike typer militære formål",
  '4020': "Skytefelt eller øvingsområde",
  '4030': "Forlegning eller leir",
  '4800': "Områder for Forsvaret kombinert i samsvar med angitte bestemmelser",
  '4900': "Områder for Forsvaret kombinert med andre angitte hovedformål",
  '5000': "Landbruks-, natur- og friluftsformål samt reindrift (LNFR) - generalisert (utgått)",
  '5001': "Landbruks-, natur- og friluftsformål samt reindrift (LNFR) (utgått)",
  '5100': "LNFR-areal for nødvendige tiltak for landbruk og reindrift og gårdstilknyttet næringsvirksomhet basert på gårdens ressursgrunnlag",
  '5110': "Landbruk",
  '5111': "Jordbruk",
  '5112': "Skogbruk",
  '5113': "Seterområde",
  '5114': "Gartneri",
  '5115': "Pelsdyranlegg (utgått)",
  '5120': "Naturformål",
  '5130': "Friluftsformål",
  '5140': "Reindrift",
  '5200': "LNFR-areal for spredt bolig- fritids- eller næringsbebyggelse, mv",
  '5210': "Spredt boligbebyggelse",
  '5220': "Spredt fritidsbebyggelse",
  '5230': "Spredt næringsbebyggelse",
  '5300': "Naturvern",
  '5400': "Jordvern",
  '5500': "Særlige landskapshensyn",
  '5600': "Vern av kulturmiljø eller kulturminne",
  '5900': "Områder for landbruks-, natur- og friluftsformål samt reindrift (LNFR) kombinert med andre angitte hovedformål",
  '6000': "Bruk og vern av sjø og vassdrag med tilhørende strandsone - generalisert (utgått)",
  '6001': "Bruk og vern av sjø og vassdrag med tilhørende strandsone",
  '6100': "Ferdsel",
  '6110': "Ankringsområde",
  '6120': "Opplagsområde",
  '6130': "Riggområde",
  '6140': "Massedeponi i sjø og vassdrag",
  '6200': "Farleder",
  '6210': "Skipsled (utgått)",
  '6211': "Hoved- og biled",
  '6220': "Havneområde i sjø",
  '6230': "Småbåthavn",
  '6240': "Bøyehavn",
  '6300': "Fiske",
  '6310': "Fiskeområde",
  '6320': "Låssettingsplasser",
  '6330': "Gytefelt eller oppvekstområde for yngel",
  '6400': "Akvakultur",
  '6410': "Akvakulturanlegg i sjø og vassdrag",
  '6420': "Akvakulturanlegg i sjø og vassdrag med tilhørende landanlegg",
  '6430': "Fangstbasert levendelagring",
  '6500': "Drikkevann",
  '6600': "Naturområde (utgått)",
  '6610': "Naturområde i sjø og vassdrag",
  '6620': "Naturområde i sjø og vassdrag med tilhørende strandsone",
  '6700': "Friluftsområde (utgått)",
  '6710': "Friluftsområde i sjø og vassdrag",
  '6720': "Friluftsområde i sjø og vassdrag med tilhørende strandsone",
  '6730': "Småbåtanlegg i sjø og vassdrag (utgått)",
  '6740': "Småbåtanlegg i sjø og vassdrag med tilhørende strandsone (utgått)",
  '6750': "Uthus/naust/badehus (utgått)",
  '6760': "Idrett og vannsport",
  '6770': "Badeområde",
  '6800': "Bruk og vern av sjø og vassdrag med tilhørende strandsone kombinert i samsvar med angitte bestemmelser",
  '6900': "Bruk og vern av sjø og vassdrag med eller uten tilhørende strandsone kombinert med andre angitte hovedformål",

  // Eldre reguleringsplaner etter plan- og bygningsloven 1985 (tresifrede koder)
  '100': "Byggeområde",
  '101': "Bybebyggelse",
  '102': "Tettbebyggelse",
  '110': "Boligområde",
  '120': "Senterområde",
  '130': "Erverv",
  '131': "Forretning",
  '132': "Kontor",
  '133': "Industri",
  '134': "Lager",
  '140': "Fritidsbebyggelse",
  '150': "Offentlig bygning",
  '155': "Bygn. med særskilt allmennyttig formål",
  '160': "Kommunaltekniske anlegg",
  '161': "Grav- og urnelund",
  '162': "Avfallsbehandling",
  '163': "Kommunalteknisk virksomhet",
  '170': "Friområde",
  '171': "Idrettsanlegg",
  '172': "Park/turvei",
  '173': "Skiløype",
  '190': "Annet byggeområde",
  '200': "Landbruks-, Natur- og Friluftsområde",
  '210': "LNF-område",
  '220': "LNF-område m/spredt bebyggelse",
  '221': "LNF-område m/spredt boligbygging",
  '222': "LNF-område m/spredt ervervsbebyggelse",
  '223': "LNF-område m/spredt fritidsbebyggelse",
  '300': "Område for råstoffutvinning",
  '310': "Gruvedrift",
  '320': "Masseuttak",
  '330': "Myrarealer",
  '400': "Område som er/skal båndlegges",
  '410': "Båndlegging etter lov om naturvern",
  '420': "Båndlegging etter lov om kulturminner",
  '460': "Båndlegges for  forsvaret",
  '470': "Område som skal reguleres etter PBL",
  '490': "Båndlegging etter annet lovverk",
  '499': "Båndlegging etter flere lovverk",
  '500': "Område for vern av sjø/vassdrag",
  '510': "Vann med restriksjon (drikkevannskilde)",
  '520': "Vannareal for alment friluftsliv",
  '521': "Småbåthavn",
  '522': "Idrettsområde",
  '530': "Vannareal for almen flerbruk",
  '531': "Ferdselsområde",
  '532': "Fiskeområde",
  '533': "Akvakulturområde",
  '540': "LNF-område i sjø og vassdrag",
  '541': "Friluftsområde i sjø og vassdrag",
  '542': "Naturområde i sjø og vassdrag",
  '590': "Annen særskilt bruk eller vern",
  '600': "Viktige ledd i kommunikasjonssystemet",
  '610': "Veiareal",
  '620': "Parkering",
  '630': "Fotgjengerstrøk",
  '631': "Bilfritt trafikkareal",
  '632': "Gang- og sykkelareal",
  '640': "Terminal",
  '641': "Terminalbygg",
  '650': "Jernbaneareal",
  '660': "Sporveisareal",
  '670': "Flyplass",
  '680': "Havn",
};
